### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by jpsml** [paroj/ObjRecPoseEst#5]
This error is ocurring when I run main_train_dagnet for the first time. Do you have any clue of how to solve it?

Traceback (most recent call last):
  File "main_train_dagnet.py", line 1520, in <module>
    linemod_train_realandsynth_main(cfgparser)
  File "main_train_dagnet.py", line 1378, in linemod_train_realandsynth_main
    visNetworkFiltersMontage(descrNet,resPath+startTimePidStr+"_filters_init.png")
  File "E:\ObjRecPoseEst-master\src\util\vis.py", line 264, in visNetworkFiltersMontage
    visFilterMontageOfLayer(wvals,fileName=layerFN,windowName=windowName)
  File "E:\ObjRecPoseEst-master\src\util\vis.py", line 217, in visFilterMontageOfLayer
    wAll = numpy.zeros((numRows*rowHeight,numCols*colWidth),dtype=numpy.float32)
TypeError: 'numpy.float64' object cannot be interpreted as an index

**Comment by Nemokang** [comment]
It seems that I am facing the same problems as you have experienced.Everything begins with the error 
in "fractNoise = cv2.medianBlur(fractNoise,3)" .Maybe errors come from our version of theano......

**Comment by Nemokang** [comment]
I have changed my version of numpy ,scipy and theano and fix errors successfully.
My current version : 
NumPy 1.11
SciPy 0.16
theano 0.8
